import type { TalkDetails } from "@/components/Schedule/types";

export const timelineData: TalkDetails[] = [
  {
    id: 1,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "8:00",
    timeTo: "8:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 2,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "9:00",
    timeTo: "9:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 3,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "10:00",
    timeTo: "10:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 4,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "11:00",
    timeTo: "11:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 5,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "12:00",
    timeTo: "12:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 6,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "13:00",
    timeTo: "13:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 7,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "15:00",
    timeTo: "15:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    id: 8,
    author: "Chris Lilley ",
    title: "Opening Keynote",
    date: "24 03 2023",
    timeFrom: "16:00",
    timeTo: "16:30",
    picture: "https://s3.eu-central-1.amazonaws.com/www.warsawjs.com/static/images/people/tejas-kumar.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];
